### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by dafnarosenblum** [botim/backend#1]
There's no authentication implementation currently.

**Comment by mderazon** [comment]
To sum up some of the discussion in Slack about this.
User will be able to "verify" their account by tweeting something that will contain some random key that we generated and by doing that we'll know that they are who they say they are.

### Flow
1. User downloads and installs the extension
2. Extension obtains some unique identifier like uuid or something of that sort from the server and stores in localstorage
3. User tries to verify their account, we generate a _token_ derived from the uuid somehow, maybe by hashing the uuid with sha256 or some other secure 1-way hash function. That key will serve as the _public key_ for that user.
4. Extension asks the user to tweet something that contains the public key
5. User tweets, extension calls the `/verify` endpoint (name tbd) and the backend looks into users tweets to see if it can find the relevant tweet and verify the user. We mark the token and public key pairs as "verified" in database
6. Once user is verified, the extension will send the token in the header on every request

### Notes
1. Only report reqests will need to actually contain the token in header, other "read only" requests that only obtain information will not need the token
2. Need to see how the backend can obtain the list of tweets for the user without having an api key - It will most likely also have to do DOM parsing, but the problem is that Twitter could more easily block the server ip.
3. This flow would almost be :100:  if we didn't have the case where the user can install the extension on a different browser or can wipe the localstorage where we save the token. With the above flow, in the case of wipe, they user will have to tweet again - Not so good. In order to solve this, once verified, we'll need to ask the user to create a password so we can sync their identity across multiple browsers. When installing on a new browser, the user will enter their password and we'll know that they've already authetnicated (we match the password with the user twitter id)

Step 3 complicates things a little...

WDYT ?

**Comment by liorn** [comment]
1. I think handling deleted storage/different browser is optional, let's start without it. Also, using `chrome.storage` in the chrome extension will sync this token across all Chrome browsers... so if the user uses the extension from another machine under his account we're good.
2. This scheme would fail for private twitter accounts; if we want to handle this, we can automatically follow any incoming request (from the botim account) and ask the user to approve us. But, same as 1, imho not crucial right now

Otherwise, looks good. Waiting with issue #7 until this is finalized...

**Comment by mderazon** [comment]
> Also, using chrome.storage in the chrome extension will sync this token across all Chrome browsers

Wasn't aware of this, if that's the case then it solves our issue very well

> This scheme would fail for private twitter accounts

That's probably fine for now

So only weak point is server parsing public tweets and getting blocked by Twitter, but we can worry about that if / when it comes.

Not sure i'll have time over the weekend to work on this, will try Sunday

**Comment by eranshmil** [comment]
This feature is not needed anymore.
Thanks for your contribution and help!
